Add lpp-advanced-config
vessl-ai/helm-charts pull request #62
Opened 2024-08-23 10:20 UTC by Namnamseo

기존 installation을 변경하고 싶으면

```yaml
local-path-provisioner:
# ...
  configmap:
    create: false # <-

lpp-advanced-config: # 이 단락 추가
  enabled: true # <-
  xfs_quota:
    size: 10g # <-
```

이렇게 세 개 만져주면 됩니다.

2024-08-29 02:00 UTC, cooco119 requested changes

2024-08-29 02:00 UTC, cooco119 commented on charts/vessl/charts/lpp-advanced-config/templates/config-map.yaml
> +{{- if .Values.xfs_quota.enabled }}
개인적으로는 If문 하나에 관련된 것들이 한번에 모여있는걸 선호합니다

```
{{- if .Values.xfs_quota.enabled }}

## setup
## teardown
## helperPod.yaml

{{- else }}
## setup
## teardown
## helperPod.yaml
```

이유는, 해당 맥락이 모여있는게 이해하기 더 쉽고 찾기도 더 쉬운 것 같습니다.

인지의 과정이,
'teardown 영역으로 가서 enabled 되었는지 보자' 보다는,
'enable안되었을때에 teardown이 어떻게 동작하는지 보자'가 더 코드가 chunk로 몰려있어서 읽기 편한 것 같아요

2024-08-29 02:00 UTC, cooco119 commented on charts/vessl/charts/lpp-advanced-config/values.yaml
> +  enabled: false
여기는 default가 false인데 아래 `charts/vessl/values.yaml`에서는 true여서 하나로 맞춰주세요

2024-08-29 02:00 UTC, cooco119 commented on charts/vessl/charts/lpp-advanced-config/files/xfs_quota_setup.sh
> +sleep 10 # TODO: remove me
why leave TODO?

2024-08-29 02:00 UTC, cooco119 commented on charts/vessl/charts/lpp-advanced-config/files/xfs_quota_teardown.sh
> +sleep 10 # TODO: remove me
Why leave TODO?

2024-08-29 02:00 UTC, cooco119 commented on charts/vessl/charts/lpp-advanced-config/files/xfs_quota_setup.sh
> +        xfs_quota -x -c "limit -p bhard=${XFS_QUOTA_SIZE} ${PROJ_NAME}" "${XFS_NAME}"
XFS_QUOTA_SIZE가 string으로 그냥 들어오는 것 같은데 검증하지 않아도 될까요?

2024-08-30 04:54 UTC, Namnamseo commented on charts/vessl/charts/lpp-advanced-config/files/xfs_quota_setup.sh
> +sleep 10 # TODO: remove me
because I forgot 💀

2024-08-30 05:12 UTC, Namnamseo commented on charts/vessl/charts/lpp-advanced-config/templates/config-map.yaml
> +{{- if .Values.xfs_quota.enabled }}
저도 이걸 양쪽으로 다 해 보면서 고민을 좀 했는데요,

* 예를 들어 setup에 공통적으로 필요한 작업이 생겼다 하면, 위쪽엔 업데이트하고 아래쪽은 빼먹기 쉬운 것 같았음
* enable되었을 때 각 부분이 뭐가 어떻게 바뀌는 건지가 잘 안 보임

이런 고민으로 일단은 이렇게 올렸습니다.
근데 말씀하신대로 enable되었을 때의 전반적인 플로우(setup과 teardown이 어떻게 collaborate하는지)가 안 보인다는 심각한 단점은 있습니다.

2024-08-30 05:13 UTC, Namnamseo commented on charts/vessl/charts/lpp-advanced-config/values.yaml
> +  enabled: false
대체 왜 그랬을까요... 🫠

2024-08-30 05:45 UTC, Namnamseo commented on charts/vessl/charts/lpp-advanced-config/files/xfs_quota_setup.sh
> +        xfs_quota -x -c "limit -p bhard=${XFS_QUOTA_SIZE} ${PROJ_NAME}" "${XFS_NAME}"
이게 bash가 아니라 sh에서 돌아가는 거라 패턴 매칭이 좀 번거로워가지고 빼 놓긴 했는데요,
`grep -E`(extended regex)로 하면 못할 것도 없네요.

검증하도록 수정했습니다.

2024-08-30 11:13 UTC, Namnamseo commented on charts/vessl/charts/lpp-advanced-config/files/xfs_quota_setup.sh
> +        xfs_quota -x -c "limit -p bhard=${XFS_QUOTA_SIZE} ${PROJ_NAME}" "${XFS_NAME}"
테스트해봤는데 잘 되네용!!!

2024-09-02 01:03 UTC, cooco119 commented on charts/vessl/charts/lpp-advanced-config/templates/config-map.yaml
> +{{- if .Values.xfs_quota.enabled }}
넵 일단 고고하시죠

저의 우려는 if문이 세번 나오는 것이었습니다 ㅋㅋㅋ

2024-09-02 01:06 UTC, cooco119 approved these changes
1개의 마이너 커멘트 남기고 우선 고고합니다!

2024-09-02 01:06 UTC, cooco119 commented on charts/vessl/charts/lpp-advanced-config/files/xfs_quota_setup.sh
> +    if ! echo "${XFS_QUOTA_SIZE}" | grep -q -E '^[1-9][0-9]*[kmg]?$'
TB는 괜찮겠죠? ㅎㅎㅎㅎ 

나중에 TB를 추가하고싶으면 여기를 어떻게 하면 쉽게 찾을 수 있을까요 

이 검증하는 내용을 함수로 빼놓으면 좀 더 찾기 쉬우려나

2024-09-02 01:54 UTC, Namnamseo commented on charts/vessl/charts/lpp-advanced-config/files/xfs_quota_setup.sh
> +    if ! echo "${XFS_QUOTA_SIZE}" | grep -q -E '^[1-9][0-9]*[kmg]?$'
TB는... 일단 되는지부터 봐야 할 것 같군요

함수 분리는 해 놓겠습니다

2024-09-02 01:57 UTC, merged